/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "colors-nile-blue-primary-100": "var(--colors-nile-blue-primary-100)",
        "colors-nile-blue-primary-200": "var(--colors-nile-blue-primary-200)",
        "colors-nile-blue-primary-300": "var(--colors-nile-blue-primary-300)",
        "colors-nile-blue-primary-400": "var(--colors-nile-blue-primary-400)",
        "colors-nile-blue-primary-50": "var(--colors-nile-blue-primary-50)",
        "colors-nile-blue-primary-500": "var(--colors-nile-blue-primary-500)",
        "colors-nile-blue-primary-600": "var(--colors-nile-blue-primary-600)",
        "colors-nile-blue-primary-700": "var(--colors-nile-blue-primary-700)",
        "colors-nile-blue-primary-800": "var(--colors-nile-blue-primary-800)",
        "colors-nile-blue-primary-900": "var(--colors-nile-blue-primary-900)",
        "colors-nile-blue-primary-950": "var(--colors-nile-blue-primary-950)",
        "main-colours-error": "var(--main-colours-error)",
        "main-colours-grayscale-dark-gray-5": "var(--main-colours-grayscale-dark-gray-5)",
        "main-colours-grayscale-light-gray-1": "var(--main-colours-grayscale-light-gray-1)",
        "main-colours-grayscale-medium-dark-gray-4": "var(--main-colours-grayscale-medium-dark-gray-4)",
        "main-colours-grayscale-medium-gray-3": "var(--main-colours-grayscale-medium-gray-3)",
        "main-colours-grayscale-medium-light-gray-2": "var(--main-colours-grayscale-medium-light-gray-2)",
        "main-colours-grayscale-very-dark-gray-6": "var(--main-colours-grayscale-very-dark-gray-6)",
        "main-colours-main-body-text": "var(--main-colours-main-body-text)",
        "main-colours-primary": "var(--main-colours-primary)",
        "main-colours-primary-100": "var(--main-colours-primary-100)",
        "main-colours-primary-200": "var(--main-colours-primary-200)",
        "main-colours-primary-300": "var(--main-colours-primary-300)",
        "main-colours-primary-400": "var(--main-colours-primary-400)",
        "main-colours-primary-500": "var(--main-colours-primary-500)",
        "main-colours-primary-600": "var(--main-colours-primary-600)",
        "main-colours-secondary": "var(--main-colours-secondary)",
        "main-colours-tertiary": "var(--main-colours-tertiary)",
        "main-colours-whitelist-cards-100": "var(--main-colours-whitelist-cards-100)",
        "main-colours-whitelist-cards-tagged-colour": "var(--main-colours-whitelist-cards-tagged-colour)",
        "main-colours-whitelist-devices-100": "var(--main-colours-whitelist-devices-100)",
        "main-colours-whitelist-devices-tagged-colour": "var(--main-colours-whitelist-devices-tagged-colour)",
        "main-colours-whitelist-groups-100": "var(--main-colours-whitelist-groups-100)",
        "main-colours-whitelist-groups-tagged-colour": "var(--main-colours-whitelist-groups-tagged-colour)",
      },
      fontFamily: {
        "form-title": "var(--form-title-font-family)",
        h1: "var(--h1-font-family)",
        h2: "var(--h2-font-family)",
        h3: "var(--h3-font-family)",
        h4: "var(--h4-font-family)",
        hyperlink: "var(--hyperlink-font-family)",
        "main-body-text": "var(--main-body-text-font-family)",
        "main-small-text": "var(--main-small-text-font-family)",
        "small-link": "var(--small-link-font-family)",
        "small-text": "var(--small-text-font-family)",
      },
    },
  },
  plugins: [],
};